version: "3.6"

services:
  app:
    image: ghcr.io/gumbo-millennium/website/codespaces
    volumes:
      - ..:/workspace:cached
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0
    expose:
      - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: vscode
      MYSQL_USER: vscode
      MYSQL_PASSWORD: vscode

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - "1025"
      - "8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - "80"
    environment:
      PMA_HOST: environment
      PMA_USER: environment
      PMA_PASSWORD: environment
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    expose:
      - "6379"
    environment:
      PMA_HOST: environment
      PMA_USER: environment
      PMA_PASSWORD: environment
    depends_on:
      - mysql
