name: Prebuild devcontainer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**/*

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/gumbo-millennium/website/devcontainer

jobs:
  build:
    name: Build devcontainer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}

      - name: Publish the devcontainer
        if: github.event_name == 'push'
        run: docker push ${{ env.IMAGE_NAME }}
